# Generated by Django 5.1.5 on 2025-01-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('desc', models.TextField(verbose_name='Описание задачи')),
                ('date_to', models.DateTimeField(auto_now_add=True, verbose_name='До скольки выполнить?')),
                ('time_register', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archive', 'Archive')], default='active', max_length=20, verbose_name='Статус задачи')),
            ],
        ),
    ]
