# Generated by Django 5.1.5 on 2025-01-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_to',
            field=models.DateTimeField(verbose_name='До скольки выполнить?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_register',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
